#!/bin/bash

TEST_FILES=("2_dijkstra_freeze.yaml" "2_dtw_freeze.yaml" "dijkstra_freeze.yaml" "dtw_freeze.yaml" "dtw_mpeg_freeze.yaml")
TIMER=60 

for CONFIG_FILE in "${TEST_FILES[@]}"; do
    
    OUTPUT_DIR="${CONFIG_FILE%.*}"
    rm -rf "${OUTPUT_DIR}"
    COMMAND_STRING="nohup hemps-run ${CONFIG_FILE} ${TIMER}"
    eval "$COMMAND_STRING &" 
    sleep 0.5
done

jobs