hw:
  page_size_KB:  64
  tasks_per_PE: 1
  repository_size_MB:  1
  physical_channels: 2
  model_description: hybrid
  noc_buffer_size: 8
  mpsoc_dimension: [4,4]
  cluster_dimension: [4,4]
  master_location: LT
  gray_area:
    rows: [2]
    cols: [0]
  open_port:
    - port: [Injector,90,0,3,N,0,0,W] 
    - port: [io_peripheral,80,3,3,N]
apps:
  - name: prod_cons_IO
    start_time_ms: 0
    secure: yes
    static_mapping:
      prod: [1,0]
      cons: [2,0]
